
name: Deploy to Yandex.Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Автоматически создаем файл .env из того самого большого секрета
      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Deploy Function
        uses: yc-actions/yc-sls-function@v4
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SECRET_KEY }}
          folder-id: ${{ secrets.YANDEX_FOLDER_ID }}
          function-name: 'storage-bot-worker'
          runtime: 'nodejs22'
          memory: '256Mb'
          execution-timeout: '60s'
          entrypoint: 'index.handler' # Точка входа в твоем index.js
          environment: |
            APP_DOMAIN=${{ vars.APP_DOMAIN }}
            BOT_USERNAME='leshiy_storage_bot'
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}